export const CATEGORY_SEARCH_QUERIES: Record<string, string[]> = {
  'bom-dia': [
    'sunrise',
    'morning coffee',
    'good morning nature',
    'sunrise mountains',
    'morning light window',
    'sunrise field',
  ],
  'boa-tarde': [
    'afternoon sun',
    'summer afternoon',
    'golden hour field',
    'afternoon coffee',
    'warm sunlight',
    'golden hour beach',
  ],
  'boa-noite': [
    'night sky stars',
    'moon night',
    'city lights night',
    'starry sky',
    'peaceful night',
    'moonlight nature',
  ],
  cristao: [
    'bible',
    'church',
    'cross faith',
    'prayer hands',
    'sunlight church',
    'candle faith',
  ],
  motivacional: [
    'mountain summit',
    'ocean waves',
    'sunrise hiking',
    'inspiring landscape',
    'strength nature',
    'road ahead',
  ],
  amor: [
    'couple romantic',
    'roses love',
    'hearts',
    'sunset couple',
    'romantic date',
    'holding hands',
  ],
};

export const PHRASE_BANK: Record<string, string[]> = {
  'bom-dia': [
    'Bom dia! Que hoje seja um dia leve e cheio de boas surpresas.',
    'Acorde, agradeça e sorria: um novo dia começou.',
    'Bom dia! Que a sua manhã seja tão bonita quanto seus sonhos.',
    'Cada manhã é uma nova chance de recomeçar. Bom dia!',
    'Que a paz do amanhecer more no seu coração hoje. Bom dia!',
    'Bom dia! Respire fundo, hoje vai ser um ótimo dia.',
    'Levante-se com fé e siga em frente. Bom dia!',
    'Bom dia! Que a força para hoje venha da esperança de ontem.',
    'Um novo dia, uma nova oportunidade de ser feliz. Bom dia!',
    'Bom dia! Que o sol de hoje aqueça seus planos e seus sonhos.',
    'A vida começa de novo todo dia às 6 da manhã. Bom dia!',
    'Bom dia! Comece o dia com um sorriso, o resto se ajeita.',
    'Que hoje você colha o que semeou com carinho. Bom dia!',
    'Bom dia! Gratidão pela vida e por mais um amanhecer.',
    'Hoje é um ótimo dia para ser feliz. Bom dia!',
    'Bom dia! Que sua manhã seja repleta de coisas boas.',
    'O sol nasceu pra você também. Bom dia!',
    'Bom dia! Encha seu dia de coisas boas e pessoas melhores ainda.',
    'Que a alegria seja a primeira coisa que você sinta hoje. Bom dia!',
    'Bom dia! Um café, um sorriso e a certeza de que vai dar tudo certo.',
    'Desperte com propósito, viva com paixão. Bom dia!',
    'Bom dia! Que Deus abençoe cada passo do seu dia.',
    'Simplesmente respire e comece. Bom dia!',
    'Bom dia! O melhor presente do mundo é acordar e poder tentar de novo.',
    'Que o seu dia seja tão especial quanto você. Bom dia!',
    'Bom dia! Vista-se de fé e caminhe com confiança.',
    'A manhã pede café, o dia pede coragem. Bom dia!',
    'Bom dia! Que cada amanhecer te lembre que tudo pode melhorar.',
  ],
  'boa-tarde': [
    'Boa tarde! Que o restante do seu dia seja leve e produtivo.',
    'Boa tarde! Renove as energias e siga em frente.',
    'Que essa tarde traga calma pro seu coração. Boa tarde!',
    'Boa tarde! Um respiro no meio do dia pra continuar com força.',
    'A tarde é o momento perfeito pra sorrir de novo. Boa tarde!',
    'Boa tarde! Que tudo o que falta do seu dia seja bom.',
    'Continue, você já venceu metade do dia. Boa tarde!',
    'Boa tarde! Que a paz do sol da tarde te acompanhe.',
    'Um cafezinho da tarde pra recarregar as energias. Boa tarde!',
    'Boa tarde! Siga confiante, o melhor ainda está por vir hoje.',
    'Que sua tarde seja tranquila como um entardecer. Boa tarde!',
    'Boa tarde! Gratidão por mais essa metade de dia vivida.',
    'A tarde pede leveza. Desacelere um pouco. Boa tarde!',
    'Boa tarde! Que essa pausa te dê força pro resto do dia.',
    'Vai dar tudo certo, continue. Boa tarde!',
    'Boa tarde! Que o sol da tarde ilumine seus próximos passos.',
    'Uma tarde boa começa com um pensamento bom. Boa tarde!',
    'Boa tarde! Que a sua tarde seja tão especial quanto a manhã foi.',
    'Respire, o dia ainda tem coisas boas guardadas. Boa tarde!',
    'Boa tarde! Siga com fé, o caminho está sendo feito.',
  ],
  'boa-noite': [
    'Boa noite! Que seus sonhos sejam tão tranquilos quanto o céu estrelado.',
    'Boa noite! Descanse, amanhã é um novo recomeço.',
    'Que a noite traga paz pro seu coração. Boa noite!',
    'Boa noite! Durma em paz, você fez o seu melhor hoje.',
    'A noite chegou pra te lembrar que está tudo bem descansar. Boa noite!',
    'Boa noite! Que os anjos cuidem do seu sono.',
    'Solte as preocupações e descanse. Boa noite!',
    'Boa noite! Amanhã o sol nasce de novo, e você também recomeça.',
    'Que essa noite seja de paz e sono tranquilo. Boa noite!',
    'Boa noite! Gratidão por mais um dia vivido intensamente.',
    'Durma bem, sonhe alto. Boa noite!',
    'Boa noite! Que o silêncio da noite acalme sua alma.',
    'Descansar também é produtivo. Boa noite!',
    'Boa noite! Que amanhã seja ainda melhor que hoje.',
    'Feche os olhos em paz, o dia de hoje já valeu a pena. Boa noite!',
    'Boa noite! Que suas estrelas iluminem seus sonhos.',
    'A noite é o tempo de recarregar pra um novo dia. Boa noite!',
    'Boa noite! Descanse o corpo, acalme a mente.',
  ],
  cristao: [
    'O Senhor é o meu pastor, nada me faltará. Boa noite!',
    'Confie no Senhor de todo o coração. Bom dia!',
    'Tudo posso naquele que me fortalece. Bom dia!',
    'A alegria do Senhor é a nossa força. Bom dia!',
    'Entrega o teu caminho ao Senhor e ele agirá. Boa noite!',
    'Deus é o nosso refúgio e fortaleza. Bom dia!',
    'Em tudo dai graças. Boa tarde!',
    'O Senhor está perto de todos os que o invocam. Boa noite!',
    'Fé é a certeza daquilo que esperamos. Bom dia!',
    'O Senhor renova as minhas forças a cada manhã. Bom dia!',
    'Lança tua ansiedade sobre Ele, porque Ele tem cuidado de ti. Boa noite!',
    'Graças a Deus por mais um dia de vida. Bom dia!',
    'A paz de Deus guarde o seu coração hoje. Boa tarde!',
    'O amor de Deus é eterno e fiel. Bom dia!',
    'Buscai primeiro o Reino de Deus. Bom dia!',
    'Deus nunca chega atrasado. Confie no tempo dEle. Boa noite!',
    'O Senhor é a minha luz e a minha salvação. Bom dia!',
    'Sonhe grande, ore mais ainda. Bom dia!',
  ],
  motivacional: [
    'Grandes conquistas exigem grandes coragens. Bom dia!',
    'Acredite: você é mais forte do que imagina.',
    'O sucesso é a soma de pequenos esforços repetidos todos os dias.',
    'Não pare quando estiver cansado, pare quando tiver terminado.',
    'Sonhe grande e ouse falhar tentando.',
    'Cada dia é uma nova chance de mudar sua vida.',
    'A disciplina é a ponte entre metas e conquistas.',
    'Foque no progresso, não na perfeição.',
    'Você não precisa ser perfeito, precisa ser persistente.',
    'Grandes coisas nunca vieram de zonas de conforto.',
    'O único lugar onde o sucesso vem antes do trabalho é no dicionário.',
    'Acredite no processo. Confie na sua caminhada.',
    'Transforme obstáculos em degraus.',
    'Sua única competição é quem você foi ontem.',
    'A persistência realiza o impossível.',
    'Comece onde você está, use o que você tem, faça o que você pode.',
    'Motivação te faz começar. Hábito te faz continuar.',
    'Vá em frente: seus sonhos não têm data de validade.',
    'A jornada de mil quilômetros começa com um único passo.',
    'Não deixe que o medo escolha o seu destino.',
  ],
  amor: [
    'O amor verdadeiro não tem pressa, tem paciência.',
    'Amar é encontrar na felicidade do outro a própria felicidade.',
    'Você é o melhor capítulo da minha história.',
    'O amor é a única coisa que cresce quando é dividida.',
    'Ao seu lado, qualquer lugar é o lugar certo.',
    'Amar é escolher todos os dias a mesma pessoa.',
    'O seu amor transforma meus dias comuns em especiais.',
    'Onde há amor verdadeiro, não há espaço para medo.',
    'Você é meu lugar favorito no mundo.',
    'O amor não se vê com os olhos, mas com o coração.',
    'Contigo, até o silêncio é bom.',
    'Amar você é a parte mais fácil da minha vida.',
    'O melhor de mim eu encontrei quando te encontrei.',
    'Que o nosso amor seja sempre assim: simples e verdadeiro.',
    'Você é a razão do meu sorriso mais bonito.',
    'Amor é isso: querer o bem do outro mais que o seu.',
  ],
};
