export const CATEGORY_SEARCH_QUERIES: Record<string, string[]> = {
  'bom-dia': [
    'sunrise',
    'morning coffee',
    'good morning nature',
    'sunrise mountains',
    'morning light window',
    'sunrise field',
  ],
  'boa-tarde': [
    'afternoon sun',
    'summer afternoon',
    'golden hour field',
    'afternoon coffee',
    'warm sunlight',
    'golden hour beach',
  ],
  'boa-noite': [
    'night sky stars',
    'moon night',
    'city lights night',
    'starry sky',
    'peaceful night',
    'moonlight nature',
  ],
  cristao: [
    'bible',
    'church',
    'cross faith',
    'prayer hands',
    'sunlight church',
    'candle faith',
  ],
  motivacional: [
    'mountain summit',
    'ocean waves',
    'sunrise hiking',
    'inspiring landscape',
    'strength nature',
    'road ahead',
  ],
  amor: [
    'couple romantic',
    'roses love',
    'hearts',
    'sunset couple',
    'romantic date',
    'holding hands',
  ],
};

export interface CategoryStyle {
  header: string;
  color: string;
}

export const CATEGORY_STYLES: Record<string, CategoryStyle> = {
  'bom-dia': { header: 'Bom dia,', color: '#FFD166' },
  'boa-tarde': { header: 'Boa tarde,', color: '#FF8C42' },
  'boa-noite': { header: 'Boa noite,', color: '#7C9EFF' },
  cristao: { header: 'Tenha fé,', color: '#C9A7EB' },
  motivacional: { header: 'Vai fundo,', color: '#6EE7B7' },
  amor: { header: 'Com amor,', color: '#FF7A9C' },
};

export const PHRASE_BANK: Record<string, string[]> = {
  'bom-dia': [
    'Que hoje seja um dia leve e cheio de boas surpresas.',
    'Acorde, agradeça e sorria: um novo dia começou.',
    'Que a sua manhã seja tão bonita quanto seus sonhos.',
    'Cada manhã é uma nova chance de recomeçar.',
    'Que a paz do amanhecer more no seu coração hoje.',
    'Respire fundo, hoje vai ser um ótimo dia.',
    'Levante-se com fé e siga em frente.',
    'Que a força para hoje venha da esperança de ontem.',
    'Um novo dia, uma nova oportunidade de ser feliz.',
    'Que o sol de hoje aqueça seus planos e seus sonhos.',
    'A vida começa de novo todo dia às 6 da manhã.',
    'Comece o dia com um sorriso, o resto se ajeita.',
    'Que hoje você colha o que semeou com carinho.',
    'Gratidão pela vida e por mais um amanhecer.',
    'Hoje é um ótimo dia para ser feliz.',
    'Que sua manhã seja repleta de coisas boas.',
    'O sol nasceu pra você também.',
    'Encha seu dia de coisas boas e pessoas melhores ainda.',
    'Que a alegria seja a primeira coisa que você sinta hoje.',
    'Um café, um sorriso e a certeza de que vai dar tudo certo.',
    'Desperte com propósito, viva com paixão.',
    'Que Deus abençoe cada passo do seu dia.',
    'Simplesmente respire e comece.',
    'O melhor presente do mundo é acordar e poder tentar de novo.',
    'Que o seu dia seja tão especial quanto você.',
    'Vista-se de fé e caminhe com confiança.',
    'A manhã pede café, o dia pede coragem.',
    'Que cada amanhecer te lembre que tudo pode melhorar.',
  ],
  'boa-tarde': [
    'Que o restante do seu dia seja leve e produtivo.',
    'Renove as energias e siga em frente.',
    'Que essa tarde traga calma pro seu coração.',
    'Um respiro no meio do dia pra continuar com força.',
    'A tarde é o momento perfeito pra sorrir de novo.',
    'Que tudo o que falta do seu dia seja bom.',
    'Continue, você já venceu metade do dia.',
    'Que a paz do sol da tarde te acompanhe.',
    'Um cafezinho da tarde pra recarregar as energias.',
    'Siga confiante, o melhor ainda está por vir hoje.',
    'Que sua tarde seja tranquila como um entardecer.',
    'Gratidão por mais essa metade de dia vivida.',
    'A tarde pede leveza. Desacelere um pouco.',
    'Que essa pausa te dê força pro resto do dia.',
    'Vai dar tudo certo, continue.',
    'Que o sol da tarde ilumine seus próximos passos.',
    'Uma tarde boa começa com um pensamento bom.',
    'Que a sua tarde seja tão especial quanto a manhã foi.',
    'Respire, o dia ainda tem coisas boas guardadas.',
    'Siga com fé, o caminho está sendo feito.',
  ],
  'boa-noite': [
    'Que seus sonhos sejam tão tranquilos quanto o céu estrelado.',
    'Descanse, amanhã é um novo recomeço.',
    'Que a noite traga paz pro seu coração.',
    'Durma em paz, você fez o seu melhor hoje.',
    'A noite chegou pra te lembrar que está tudo bem descansar.',
    'Que os anjos cuidem do seu sono.',
    'Solte as preocupações e descanse.',
    'Amanhã o sol nasce de novo, e você também recomeça.',
    'Que essa noite seja de paz e sono tranquilo.',
    'Gratidão por mais um dia vivido intensamente.',
    'Durma bem, sonhe alto.',
    'Que o silêncio da noite acalme sua alma.',
    'Descansar também é produtivo.',
    'Que amanhã seja ainda melhor que hoje.',
    'Feche os olhos em paz, o dia de hoje já valeu a pena.',
    'Que suas estrelas iluminem seus sonhos.',
    'A noite é o tempo de recarregar pra um novo dia.',
    'Descanse o corpo, acalme a mente.',
  ],
  cristao: [
    'O Senhor é o meu pastor, nada me faltará.',
    'Confie no Senhor de todo o coração.',
    'Tudo posso naquele que me fortalece.',
    'A alegria do Senhor é a nossa força.',
    'Entrega o teu caminho ao Senhor e ele agirá.',
    'Deus é o nosso refúgio e fortaleza.',
    'Em tudo dai graças.',
    'O Senhor está perto de todos os que o invocam.',
    'Fé é a certeza daquilo que esperamos.',
    'O Senhor renova as minhas forças a cada manhã.',
    'Lança tua ansiedade sobre Ele, porque Ele tem cuidado de ti.',
    'Graças a Deus por mais um dia de vida.',
    'A paz de Deus guarde o seu coração hoje.',
    'O amor de Deus é eterno e fiel.',
    'Buscai primeiro o Reino de Deus.',
    'Deus nunca chega atrasado. Confie no tempo dEle.',
    'O Senhor é a minha luz e a minha salvação.',
    'Sonhe grande, ore mais ainda.',
  ],
  motivacional: [
    'Grandes conquistas exigem grandes coragens.',
    'Você é mais forte do que imagina.',
    'O sucesso é a soma de pequenos esforços repetidos todos os dias.',
    'Não pare quando estiver cansado, pare quando tiver terminado.',
    'Sonhe grande e ouse falhar tentando.',
    'Cada dia é uma nova chance de mudar sua vida.',
    'A disciplina é a ponte entre metas e conquistas.',
    'Foque no progresso, não na perfeição.',
    'Você não precisa ser perfeito, precisa ser persistente.',
    'Grandes coisas nunca vieram de zonas de conforto.',
    'O único lugar onde o sucesso vem antes do trabalho é no dicionário.',
    'Acredite no processo. Confie na sua caminhada.',
    'Transforme obstáculos em degraus.',
    'Sua única competição é quem você foi ontem.',
    'A persistência realiza o impossível.',
    'Comece onde você está, use o que você tem, faça o que você pode.',
    'Motivação te faz começar. Hábito te faz continuar.',
    'Seus sonhos não têm data de validade.',
    'A jornada de mil quilômetros começa com um único passo.',
    'Não deixe que o medo escolha o seu destino.',
  ],
  amor: [
    'O amor verdadeiro não tem pressa, tem paciência.',
    'Amar é encontrar na felicidade do outro a própria felicidade.',
    'Você é o melhor capítulo da minha história.',
    'O amor é a única coisa que cresce quando é dividida.',
    'Ao seu lado, qualquer lugar é o lugar certo.',
    'Amar é escolher todos os dias a mesma pessoa.',
    'O seu amor transforma meus dias comuns em especiais.',
    'Onde há amor verdadeiro, não há espaço para medo.',
    'Você é meu lugar favorito no mundo.',
    'O amor não se vê com os olhos, mas com o coração.',
    'Contigo, até o silêncio é bom.',
    'Amar você é a parte mais fácil da minha vida.',
    'O melhor de mim eu encontrei quando te encontrei.',
    'Que o nosso amor seja sempre assim: simples e verdadeiro.',
    'Você é a razão do meu sorriso mais bonito.',
    'Amor é isso: querer o bem do outro mais que o seu.',
  ],
};
